language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.3.1
  - DJANGO=1.4.5   # django-polymorphic 0.5 uses django.utils.six which is bundled as of Django 1.4.2
install:
  - if [[ "$DJANGO" == '1.3.1' ]]; then pip install django-polymorphic==0.4.0 --use-mirrors; fi
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - python runtests.py
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-fluent"
    template:
      - "%{repository}#%{build_number} (%{commit}) %{message}  --  %{build_url}"
    skip_join: true
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
